name:                IMP-lang
version:             1.0.0
github:              "AustinZhu/IMP-lang"
license:             BSD3
author:              "Austin Zhu"
maintainer:          "Author email here"
copyright:           "2021 Austin Zhu"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Github username here/IMP-lang#readme>

dependencies:
- base >= 4.7 && < 5
- parsec >= 3.1.10
- containers >= 0.6.2.1

library:
  source-dirs: src

executables:
  IMP-lang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - IMP-lang

tests:
  IMP-lang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - IMP-lang
